app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.user_login, name='user_login'),
    path('index/',views.index,name='index'),
    path('user_register/', views.user_register, name='user_register'),
    path('creer_equipe/', views.creer_equipe, name='creer_equipe'),
    path('soumission/', views.soumission, name='soumission'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('acceuil/',views.acceuil,name='acceuil'),

    path('defis/', views.list_defis, name='list_defis'),
    path('defis/add/', views.add_defi, name='add_defi'),
    path('defis/edit/<int:defi_id>/', views.edit_defi, name='edit_defi'),
    path('defis/delete/<int:defi_id>/', views.delete_defi, name='delete_defi'),

]

defi1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),  # Remplacez 'myapp' par le nom de votre application
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission
from datetime import datetime

class CustomUser(AbstractUser):
    ROLE_CHOICES = (
        ('etudiant', 'Étudiant'),
        ('organisateur', 'Organisateur'),
        ('membre_jury', 'Membre du jury'),
    )

    role = models.CharField(
        max_length=20,
        choices=ROLE_CHOICES,
        default='',
        verbose_name='Type d\'utilisateur',
    )

    class Meta:
        permissions = [
            ("can_do_something", "Can do something"),
        ]

    groups = models.ManyToManyField(Group, related_name='custom_user_groups')
    user_permissions = models.ManyToManyField(Permission, related_name='custom_user_permissions')

class Etudiant(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, primary_key=True)
    equipe = models.ForeignKey('Equipe', on_delete=models.SET_NULL, null=True)
    niveau_d_etude = models.CharField(max_length=100)
    specialite = models.CharField(max_length=100, choices=(('DSI', 'DSI'), ('CNM', 'CNM'), ('RSS', 'RSS')))
    ROLE_CHOICES = (
        ('membre', 'Membre'),
        ('adjoint', 'Adjoint'),
        ('lead', 'Lead'),
    )
    role_equipe = models.CharField(max_length=20, choices=ROLE_CHOICES, default='membre')

    def __str__(self):
        return self.user.username
    
class Equipe(models.Model):
    id_equipe = models.AutoField(primary_key=True)
    nom_equipe = models.CharField(max_length=100)

class Defi(models.Model):
    id_defi = models.AutoField(primary_key=True)
    titre_defi = models.CharField(max_length=100)
    piece_jointe = models.FileField(upload_to='chemin/vers/dossier', blank=True)
    date_publication = models.DateTimeField(default=datetime.now, blank=True)
    description = models.TextField()
    date_limite = models.DateField()
    STATUT_CHOICES = (
        ('ouvert', 'Ouvert'),
        ('ferme', 'Fermé'),
    )
    statut = models.CharField(max_length=20, choices=STATUT_CHOICES, default='ouvert')
    organisateur = models.ForeignKey('Organisateur', on_delete=models.CASCADE)

class Organisateur(models.Model):
    id_organisateur = models.AutoField(primary_key=True)
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, null=True, blank=True, related_name='organisateur_user')
    nom_organisateur = models.CharField(max_length=20, null=True)

    def __str__(self):
        return self.nom_organisateur
  
class Soumission(models.Model):
    id_soumission = models.AutoField(primary_key=True)
    equipe = models.ForeignKey(Equipe, on_delete=models.CASCADE, null=True, blank=True)
    defi = models.ForeignKey(Defi, on_delete=models.CASCADE, null=True, blank=True)
    fichier_soumis = models.FileField(upload_to='submission_files/')
    date_soumission = models.DateTimeField(auto_now_add=True)

class MembreJury(models.Model):
    id_membre_jury = models.AutoField(primary_key=True)
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, null=True, blank=True, related_name='jury_user')
    nom_membre = models.CharField(max_length=20, null=True, blank=True)

    def __str__(self):
        return self.nom_membre

class Evaluation(models.Model):
    id_evaluation = models.AutoField(primary_key=True)
    equipe = models.ForeignKey(Equipe, on_delete=models.CASCADE)
    defi = models.ForeignKey(Defi, on_delete=models.CASCADE)
    membre_jury = models.ForeignKey(MembreJury, on_delete=models.CASCADE, null=True, blank=True, related_name='jury_evaluation')
    note = models.DecimalField(max_digits=5, decimal_places=2)

class GrilleEvaluation(models.Model):
    id_grille = models.AutoField(primary_key=True)
    defi = models.ForeignKey(Defi, on_delete=models.CASCADE, null=True, blank=True, related_name='evaluation_grille')
    critere = models.CharField(max_length=100)
    note_attribuee = models.DecimalField(max_digits=5, decimal_places=2)
    coefficient = models.DecimalField(max_digits=5, decimal_places=2)

app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import *
from django.contrib.auth.decorators import login_required

class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(max_length=255, label="Nom d'utilisateur")
    email = forms.EmailField(label="Adresse email")
    password1 = forms.CharField(max_length=255, label="Mot de passe", widget=forms.PasswordInput)
    password2 = forms.CharField(max_length=255, label="Confirmez le mot de passe", widget=forms.PasswordInput)
    niveau_d_etude = forms.CharField(max_length=100, label="Niveau d'étude", required=False)
    specialite = forms.CharField(max_length=100, label="Spécialité", required=False)

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 'password2', 'niveau_d_etude', 'specialite']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].label = "Mot de passe"
        self.fields['password2'].label = "Confirmez le mot de passe"

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')
        if password1 != password2:
            raise forms.ValidationError('Les mots de passe ne correspondent pas.')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.role = 'etudiant'  # Attribuer le rôle "étudiant" par défaut
        if commit:
            user.save()
        return user

class EquipeCreationForm(forms.ModelForm):
    class Meta:
        model = Equipe
        fields = ['nom_equipe']

    leader = forms.ModelChoiceField(queryset=Etudiant.objects.filter(role_equipe='lead'), label="Leader")
    adjoint = forms.ModelChoiceField(queryset=Etudiant.objects.filter(role_equipe='adjoint'), label="Adjoint")
    membres = forms.ModelMultipleChoiceField(queryset=Etudiant.objects.all(), label="Membres de l'équipe", required=False)

    def clean_membres(self):
        membres = self.cleaned_data['membres']
        leader = self.cleaned_data.get('leader')
        adjoint = self.cleaned_data.get('adjoint')
        
        # Ajout du leader et de l'adjoint à la liste des membres
        membres = list(membres) + [leader, adjoint]

        if len(membres) < 6 or len(membres) > 8:
            raise forms.ValidationError("Le nombre total de membres d'une équipe, y compris le leader et l'adjoint, doit être entre 6 et 8.")
        
        return membres
      
from django import forms
from .models import Soumission

class SoumissionForm(forms.ModelForm):
    def __init__(self, *args, defi_choices=None, **kwargs):
        super().__init__(*args, **kwargs)
        if defi_choices:
            self.fields['defi'] = forms.ChoiceField(choices=defi_choices, label='Choisissez un défi')

    class Meta:
        model = Soumission
        fields = ['defi', 'fichier_soumis']

class DefiForm(forms.ModelForm):
        class Meta:
            model = Defi
            fields = ['titre_defi', 'piece_jointe','description', 'date_limite', 'organisateur']
            widgets = {
            'date_limite': forms.DateInput(attrs={'type': 'date'})
        }

app/templates/edit_defi.html


<!DOCTYPE html>
<html lang="en">

<body>
    <h2>Modifier le défi</h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Enregistrer les modifications</button>
    </form>
</body>
</html>

app/templates/index.html
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Créer une équipe</title>
    <style>
        .custom-input-width {
            min-width: 200px; /* Largeur minimale de l'input texte */
        }
    </style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.3/css/bulma.min.css">
</head>
<body>
    <div class="container">
        
        <div class="box">
            <h2 class="title">Créer une équipe</h2>
            <form method="post" action="{% url 'creer_equipe' %}">
                {% csrf_token %}
                <div class="columns is-mobile">
                    <div class="column">
                        <div class="field">
                            <label class="label" for="id_nom_equipe">Nom de l'équipe:</label>
                            <div class="control">
                                <input type="text" class="input is-link custom-input-width" id="id_nom_equipe" name="nom_equipe">
                            </div>
                        </div>
                    </div>
                </div>
    
                <div class="columns is-mobile">
                    <div class="column">
                        <div class="select is-link">
                            <label class="label" for="id_leader">Leader:</label>
                            <select class="form-control" id="id_leader" name="leader">
                                <option value="">Sélectionner un leader</option>
                                {% for etudiant in etudiants %}
                                    <option value="{{ etudiant.user_id }}" class="option-noir">{{ etudiant.user.username }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="column">
                        <div class="select is-link">
                            <label class="label" for="id_adjoint">Adjoint:</label>
                            <select class="form-control" id="id_adjoint" name="adjoint">
                                <option value="">Sélectionner un adjoint</option>
                                {% for etudiant in etudiants %}
                                    <option value="{{ etudiant.user_id }}" class="option-noir">{{ etudiant.user.username }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>
    
                {% for i in "1234" %}
                <div class="columns is-mobile">
                    <div class="column">
                        <div class="select is-link">
                            <label class="label" for="id_membre{{ i }}">Membre {{ i }}:</label>
                            <select class="form-control" id="id_membre{{ i }}" name="membre{{ i }}">
                                <option value="">Sélectionner membre {{ i }}</option>
                                {% for etudiant in etudiants %}
                                    <option value="{{ etudiant.user_id }}" class="option-noir">{{ etudiant.user.username }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>
                {% endfor %}
    
                <button type="submit" class="button is-primary">Créer l'équipe</button>
            </form>
        </div>
    </div>

app/templates/list_defis.html

{% block content %}
<div class="container">
    <h2>Liste des défis</h2>
    <a class="btn btn-primary mb-3" href="{% url 'add_defi' %}">Ajouter</a>
    <div class="table-responsive">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Titre</th>
                    <th scope="col">Date de publication</th>
                    <th scope="col">Date limite</th>
                    <th scope="col">Statut</th>
                    <th scope="col">Organisateur</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for defi in defis %}
                <tr>
                    <td>{{ defi.titre_defi }}</td>
                    <td>{{ defi.date_publication }}</td>
                    <td>{{ defi.date_limite }}</td>
                    <td>{{ defi.statut }}</td>
                    <td>{{ defi.organisateur }}</td>
                    <td>
                        <a href="{% url 'edit_defi' defi.id_defi %}" class="btn btn-primary btn-sm">Modifier</a>
                        <a href="{% url 'delete_defi' defi.id_defi %}" class="btn btn-danger btn-sm">Supprimer</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

app/templates/login.html
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Login Form HTML Design</title>
  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
  <div class="container-fluid form-container">
    <div class="container login-container">
        <div class="row">
            <div class="col-md-5 content-part">
                
              <img src="{% static 'images/logo-supnum2.png' %}" alt="">
              <br/><br/>
              <h2 style="color: #03224c;">Accéder au SupNum Coding Challenge Championship’2024 (S3C’2024)</h2>
               
            </div>
            <div class="col-md-7 form-part">
              <div class="row">
                 <p class="signinlink">Dont have an account <a href="{% url 'user_register' %}">Sign Up</a></p>

                <div class="col-lg-8 col-md-11 login formcol mx-auto">
                     <h3>Connecter</h3>
                    
                     <form method="post">
                        {% csrf_token %}
                        <div class="form-floating mb-3">
                          <input type="text" class="form-control" id="id_username" name="username" placeholder="Username">
                          <label for="id_username">Username</label>
                        </div>
                        <div class="form-floating mb-3">
                          <input type="password" class="form-control" id="id_password" name="password" placeholder="Password">
                          <label for="id_password">Password</label>
                        </div>
                        <div class="form-floating">
                          <button class="btn btn-primary">Login</button>
                        </div>
                      </form>

                </div>
               
              </div>
               
            </div>
        </div>
    </div>
  </div> 
</body>
</html>

app/templates/register.html
{% load static %}
<!doctype html>
  <html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Login Form HTML Design</title>  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>

<body>
  <div class="container-fluid form-container">
    <div class="container login-container">
        <div class="row">
            <div class="col-md-5 content-part">
                
                <img src="{% static 'images/logo-supnum2.png' %}" alt="">
              <br/><br/>
              <h2 style="color: #03224c;">Accéder au SupNum Coding Challenge Championship’2024 (S3C’2024)</h2>
                {% comment %} <p>Don’t waste time on tedious manual tasks. Let Automation do it for you. Simplify workflows, 
                reduce errors, and save time for solving more important problems.</p> {% endcomment %}
            </div>
            <div class="col-md-7 form-part">
              <div class="row">
                <p class="signinlink">Vous avez déjà un compte ? <a href="{% url 'user_login' %}">Connectez-vous</a></p>

                <div class="col-lg-8 col-md-11 formcol mx-auto">
                    <h3>Inscrivez-vous sur S3C</h3>
                </div>

              <div class="row">
              {% if errors %}
              <div class="alert alert-danger">
                <ul>
                  {% for error in errors %}
                  <li>{{ error }}</li>
                  {% endfor %}
                </ul>
              </div>
              {% endif %}
              <form
                method="post"
                action="{% url 'user_register' %}"
                id="registration-form"
              >
                {% csrf_token %}
              
                <div class="form-floating mb-3">
                  <input type="email" class="form-control" id="floatingInput" name="email" placeholder="Email address">
                  <label for="floatingInput">Addresse Email</label>
                </div>
                <div class="form-floating mb-3">
                  <input type="text" class="form-control" id="floatingInput" name="username" placeholder="Username">
                  <label for="floatingInput">Nom d'utilisateur</label>
                </div>
                <div class="form-floating mb-3">
                  <input type="password" class="form-control" id="floatingPassword" name="password1" placeholder="Password">
                  <label for="floatingPassword">Mot de passe</label>
                </div>
                <div class="form-floating mb-3">
                  <input type="password" class="form-control" id="floatingPassword" name="password2" placeholder="Confirm Password">
                  <label for="floatingPassword">Confirmer le mot de passe</label>
                </div>
                {% comment %} <div class="form-floating mb-3">
                  <input type="password" class="form-control" id="floatingPassword" name="matricule" placeholder="Matricule">
                  <label for="floatingPassword">Matricule</label>
                </div> {% endcomment %}
                </div>
              <div class="form-floating mb-3 etudiant-fields">
                  <select class="form-select" id="niveauEtude" name="niveau_d_etude">
                      <option value="" disabled selected>-- Sélectionner un niveau --</option>
                      <option value="L2">L2</option>
                      <option value="L3">L3</option>
                  </select>
                  <label for="niveauEtude">{{ form.niveau_d_etude.label }}</label>
              </div>
              <div class="form-floating mb-3 etudiant-fields">
                  <select class="form-select" id="specialite" name="specialite">
                      <option value="" disabled selected>-- Sélectionner une spécialité --</option>
                      <option value="RSS">RSS</option>
                      <option value="CNM">CNM</option>
                      <option value="DSI">DSI</option>
                  </select>
                  <label for="specialite">{{ form.specialite.label }}</label>
              </div>
              
              <div class="form-floating">
                <button class="btn btn-primary">Créer un compte</button>
               </div>

             </div>
            
           </div>
            
         </div>
     </div>
 </div>
</div> 

    <!-- Bootstrap JS -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
   
  </body>
</html>

app/templates/soumission.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Soumission</title>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const form = document.querySelector('form');
            form.addEventListener('submit', function (event) {
                event.preventDefault();
                fetch(form.action, {
                    method: 'POST',
                    body: new FormData(form),
                    headers: {
                        'X-CSRFToken': '{{ csrf_token }}'
                    }
                })
                .then(response => response.json())
                .then(data => {
                    if (data.success) {
                        alert('Soumission réussie!');
                        
                    } else {
                        alert('Erreur lors de la soumission.');
                    }
                })
                .catch(error => {
                    console.error('Error:', error);
                });
            });
        });
    </script>
</head>
<body>
    
    <h2>Soumission</h2>
    <form method="post" enctype="multipart/form-data" action="{% url 'soumission' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Soumettre</button>
    </form>
</body>
</html>